<?php

namespace Database\Seeders;

use App\Models\Languages;
use Illuminate\Support\Carbon;
use Illuminate\Database\Seeder;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $languages_list = [
            ["name" => "Afrikaans", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "af"],
            ["name" => "Albanian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "sq"],
            ["name" => "Amharic", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "am"],
            ["name" => "Arabic", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ar"],
            ["name" => "Aragonese", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "an"],
            ["name" => "Armenian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "hy"],
            ["name" => "Asturian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ast"],
            ["name" => "Azerbaijani", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "az"],
            ["name" => "Basque", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "eu"],
            ["name" => "Belarusian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "be"],
            ["name" => "Bengali", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "bn"],
            ["name" => "Bosnian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "bs"],
            ["name" => "Breton", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "br"],
            ["name" => "Bulgarian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "bg"],
            ["name" => "Catalan", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ca"],
            ["name" => "Central Kurdish", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ckb"],
            ["name" => "Chinese", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "zh"],
            ["name" => "Corsican", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "co"],
            ["name" => "Croatian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "hr"],
            ["name" => "Czech", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "cs"],
            ["name" => "Danish", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "da"],
            ["name" => "Dutch", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "nl"],
            ["name" => "English", "selected" => 1, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "en"],
            ["name" => "Esperanto", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "eo"],
            ["name" => "Estonian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "et"],
            ["name" => "Faroese", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "fo"],
            ["name" => "Filipino", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "fil"],
            ["name" => "Finnish", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "fi"],
            ["name" => "French", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "fr"],
            ["name" => "Galician", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "gl"],
            ["name" => "Georgian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ka"],
            ["name" => "German", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "de"],
            ["name" => "Greek", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "el"],
            ["name" => "Guarani", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "gn"],
            ["name" => "Gujarati", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "gu"],
            ["name" => "Hausa", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ha"],
            ["name" => "Hawaiian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "haw"],
            ["name" => "Hebrew", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "he"],
            ["name" => "Hindi", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "hi"],
            ["name" => "Hungarian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "hu"],
            ["name" => "Icelandic", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "is"],
            ["name" => "Indonesian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "id"],
            ["name" => "Interlingua", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ia"],
            ["name" => "Irish", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ga"],
            ["name" => "Italian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "it"],
            ["name" => "Japanese", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ja"],
            ["name" => "Kannada", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "kn"],
            ["name" => "Kazakh", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "kk"],
            ["name" => "Khmer", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "km"],
            ["name" => "Korean", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ko"],
            ["name" => "Kurdish", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ku"],
            ["name" => "Kyrgyz", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ky"],
            ["name" => "Lao", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "lo"],
            ["name" => "Latin", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "la"],
            ["name" => "Latvian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "lv"],
            ["name" => "Lingala", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ln"],
            ["name" => "Lithuanian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "lt"],
            ["name" => "Macedonian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "mk"],
            ["name" => "Malay", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ms"],
            ["name" => "Malayalam", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ml"],
            ["name" => "Maltese", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "mt"],
            ["name" => "Marathi", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "mr"],
            ["name" => "Mongolian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "mn"],
            ["name" => "Nepali", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ne"],
            ["name" => "Norwegian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "no"],
            ["name" => "Occitan", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "oc"],
            ["name" => "Oriya", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "or"],
            ["name" => "Oromo", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "om"],
            ["name" => "Pashto", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ps"],
            ["name" => "Persian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "fa"],
            ["name" => "Polish", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "pl"],
            ["name" => "Portuguese", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "pt"],
            ["name" => "Punjabi", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "pa"],
            ["name" => "Quechua", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "qu"],
            ["name" => "Romanian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ro"],
            ["name" => "Romansh", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "rm"],
            ["name" => "Russian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ru"],
            ["name" => "Scottish Gaelic", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "gd"],
            ["name" => "Serbian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "sr"],
            ["name" => "Serbo", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "sh"],
            ["name" => "Shona", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "sn"],
            ["name" => "Sindhi", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "sd"],
            ["name" => "Sinhala", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "si"],
            ["name" => "Slovak", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "sk"],
            ["name" => "Slovenian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "sl"],
            ["name" => "Somali", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "so"],
            ["name" => "Southern Sotho", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "st"],
            ["name" => "Spanish", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "es"],
            ["name" => "Sundanese", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "su"],
            ["name" => "Swahili", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "sw"],
            ["name" => "Swedish", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "sv"],
            ["name" => "Tajik", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "tg"],
            ["name" => "Tamil", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ta"],
            ["name" => "Tatar", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "tt"],
            ["name" => "Telugu", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "te"],
            ["name" => "Thai", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "th"],
            ["name" => "Tigrinya", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ti"],
            ["name" => "Tongan", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "to"],
            ["name" => "Turkish", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "tr"],
            ["name" => "Turkmen", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "tk"],
            ["name" => "Twi", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "tw"],
            ["name" => "Ukrainian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "uk"],
            ["name" => "Urdu", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ur"],
            ["name" => "Uyghur", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "ug"],
            ["name" => "Uzbek", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "uz"],
            ["name" => "Vietnamese", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "vi"],
            ["name" => "Walloon", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "wa"],
            ["name" => "Welsh", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "cy"],
            ["name" => "Western Frisian", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "fy"],
            ["name" => "Xhosa", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "xh"],
            ["name" => "Yiddish", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "yi"],
            ["name" => "Yoruba", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "yo"],
            ["name" => "Zulu", "selected" => 0, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), "code" => "zu"]
        ];
        Languages::insert($languages_list);
    }
}
